//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAuth2
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Application
    {
        public Application()
        {
            this.Provisions = new HashSet<Provision>();
        }
    
        [Display(Name="Application Id")]
     public int ApplicationId { get; set; }
        [Display(Name="Application Name")]
     public string ApplicationName { get; set; }
    
        [Display(Name="Provisions")]
     public virtual ICollection<Provision> Provisions { get; set; }
    }
}
