//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAuth2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public System.Guid TokenId { get; set; }
        public int ProvisionId { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
    
        public virtual Provision Provision { get; set; }
    }
}
